### ISSUE TITLE
Correct the search term so that it always works correctly

### ISSUE THREAD

**Issue by sampulsar** [enymawse/stasherr#4]
The search term can strip characters for computability when searching for a title. There are a couple of special ways to search for a movie or scene using there IDs that will not strip the value.  

const fullApiUrl = `${config.apiUrl}lookup/scene?term=stash:${encodeURIComponent(sceneID)}`;

**Comment by enymawse** [comment]
Keep it coming. I appreciate the feedback and would like to make this more useful.
